name: Continuous Deployment

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed

jobs:
  release_and_publish:
    if: |
      github.event.workflow_run.conclusion == 'success' && 
      (startsWith(github.event.workflow_run.head_branch, 'refs/tags/v') && github.event.workflow_run.head_branch == 'main')
    uses: ./.github/workflows/deployment.yml
    secrets: inherit