name: Main Workflow

on:
  push:
    branches:
      - main
      - dev
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
      - dev
  workflow_call:
  

jobs:
  code_quality:
    uses: ./.github/workflows/code-quality.yml

  build:
    needs: code_quality
    uses: ./.github/workflows/build.yml

  release_and_publish:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    permissions:
      contents: write
    uses: ./.github/workflows/deployment.yml
    secrets: inherit